// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5vKWI-5cypUg5REdcjPPrWwMpOYJGBjg',
    appId: '1:721748567255:web:d91504472e2d925abe7c92',
    messagingSenderId: '721748567255',
    projectId: 'todo-a7106',
    authDomain: 'todo-a7106.firebaseapp.com',
    storageBucket: 'todo-a7106.appspot.com',
    measurementId: 'G-WLVFRNWD3P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Mo4K0na-6b9RzvgAE2hLXCAHV3fC-Xg',
    appId: '1:721748567255:ios:72b1ffa9c34f0260be7c92',
    messagingSenderId: '721748567255',
    projectId: 'todo-a7106',
    storageBucket: 'todo-a7106.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Mo4K0na-6b9RzvgAE2hLXCAHV3fC-Xg',
    appId: '1:721748567255:ios:72b1ffa9c34f0260be7c92',
    messagingSenderId: '721748567255',
    projectId: 'todo-a7106',
    storageBucket: 'todo-a7106.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5vKWI-5cypUg5REdcjPPrWwMpOYJGBjg',
    appId: '1:721748567255:web:245d1def79739014be7c92',
    messagingSenderId: '721748567255',
    projectId: 'todo-a7106',
    authDomain: 'todo-a7106.firebaseapp.com',
    storageBucket: 'todo-a7106.appspot.com',
    measurementId: 'G-MQR4PEJSYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfma3AFEaYxsxkYvDgea5YxAUl_K3D1sA',
    appId: '1:721748567255:android:3196a957bc8feaeebe7c92',
    messagingSenderId: '721748567255',
    projectId: 'todo-a7106',
    storageBucket: 'todo-a7106.appspot.com',
  );

}